### ISSUE TITLE
too many files open

### ISSUE THREAD

**Issue by bryall** [nvim-lua/telescope.nvim#34] opened 2020-09-05 13:04 UTC
I have been getting the "too many files open" error, if I open telescope and just C-n and C-p  through the list, it happens everytime for me. It happens after around 50 files for me.

**Comment by tjdevries** [comment] 2020-09-05 19:00
Ha, I thought this was something else on my system -- that's good to know that someone else is experiencing it. I will see if I can figure out where the issue is coming from.

Thanks for reporting.

**Comment by tjdevries** [comment] 2020-09-05 19:02
Does it happen for a particular `builtin`?

**Comment by bryall** [comment] 2020-09-05 19:09
i mainly see it in the file based builtins (especially git_files)

**Comment by tjdevries** [comment] 2020-09-05 19:50
:+1: ty. I will see if I can track it down at some point soon.

**Comment by ltfiend** [comment] 2020-09-07 08:35
I think bat processes aren't being cleaned up which is causing this issue.

**Comment by ltfiend** [comment] 2020-09-07 08:46
changing paging to never in previewers.lua:13 seems to fix it from a bat perspective.

**Comment by bryall** [comment] 2020-09-07 14:37
i can confirm that changing the pager to "never" , I do not see that error message

**Comment by bryall** [comment] 2020-09-07 14:48
that option is in two locations, probably should fix that. the command_string in the cat previewer should grab the bat_options

**Comment by tjdevries** [comment] 2020-09-07 15:00
I think I have improved this (as well as closing the terminal when we do teardown.)

Those previewers are due for a refactor. I may do that sometime this week (we'll have to see)

**Comment by tjdevries** [comment] 2020-09-10 14:50
Closing this until someone encounters it again. Please let me know if you encounter it on latest version.

**Closed by tjdevries** 2020-09-10 14:50 UTC

**Comment by kassio** [comment] 2021-01-11 11:10
@tjdevries it's happening for me:

<img width="1828" alt="node" src="https://user-images.githubusercontent.com/120483/104173419-a41b0e80-53fd-11eb-86de-670803db869f.png">

**Comment by kassio** [comment] 2021-01-11 11:18
I had a problem with python3 provider, fixing that seems to have fixed the error above as well. 🤷

**Comment by bryceyang** [comment] 2021-01-12 17:27
<img width="881" alt="Screen Shot 2021-01-13 at 1 24 39 AM" src="https://user-images.githubusercontent.com/9302617/104349638-24488d80-553e-11eb-9db8-d786b8486520.png">

same issue here. I am using the latest version of telescope, the commit id is 6461b07.

**Comment by tjdevries** [comment] 2021-01-12 17:49
Can you try the new buffer previewers and see if the problem goes away?

**Comment by tjdevries** [comment] 2021-01-12 17:49
(the info is in the README)

**Comment by Conni2461** [comment] 2021-01-12 17:51
I was just about to comment that is the new buffer previewer who is telling that error message 😆 
What does `ulimit -n` return to you? Thats the maximum amount of file descriptors you are allowed to open on your system.

**Comment by bryceyang** [comment] 2021-01-12 18:01
@Conni2461  my fault. I am just setting up develop env on my new m1 mac.  
just checked the ulimit, it's 256 by default.  problem solved after changing ulimit to a proper value.

**Comment by tjdevries** [comment] 2021-01-12 18:07
@Conni2461 yeah, we should not error out, but just display some message "hey, we tried to open this but couldn't right now".

**Comment by tjdevries** [comment] 2021-01-12 18:07
We also may want to just do a readthrough at some point to make sure we've closed all the file descriptors

**Comment by Conni2461** [comment] 2021-01-12 18:09
Yeah and probably say. "Consider changing your `ulimit -n`."
And we are closing them as soon as we are done writing our data to the buffer previewer.

**Comment by yujinyuz** [comment] 2021-01-13 06:17
Things feel quite smoother after running `ulimit -n 1024`
